#!/usr/bin/env python3
"""Forward /trolley/center_goal directly to Nav2 NavigateToPose.

This intentionally performs NO centerline generation or path shaping.
The global path is generated by Nav2's configured planner (SmacPlanner2D
in the V4 baseline configuration).
"""

import rclpy
from action_msgs.msg import GoalStatus
from geometry_msgs.msg import PoseStamped
from nav2_msgs.action import NavigateToPose
from rclpy.action import ActionClient
from rclpy.node import Node


class TrolleyGoalForwarder(Node):
    def __init__(self):
        super().__init__('trolley_goal_forwarder')
        self.declare_parameter('goal_topic', '/trolley/center_goal')
        self.declare_parameter('action_name', '/navigate_to_pose')

        goal_topic = self.get_parameter('goal_topic').value
        action_name = self.get_parameter('action_name').value

        self._client = ActionClient(self, NavigateToPose, action_name)
        self._goal_handle = None
        self._pending_pose = None
        self.create_subscription(PoseStamped, goal_topic, self._on_goal, 10)
        self.get_logger().info(
            f'Goal forwarder ready: {goal_topic} -> {action_name} '
            '(no centerline generation)'
        )

    def _on_goal(self, msg: PoseStamped):
        self._pending_pose = msg
        if not self._client.server_is_ready():
            self.get_logger().warn('NavigateToPose server is not ready yet; waiting asynchronously.')
            self._client.wait_for_server(timeout_sec=1.0)
            if not self._client.server_is_ready():
                self.get_logger().error('NavigateToPose server still unavailable; goal not sent.')
                return

        # RViz goal semantics: a new goal replaces the previous one.
        if self._goal_handle is not None and self._goal_handle.status in (
            GoalStatus.STATUS_ACCEPTED,
            GoalStatus.STATUS_EXECUTING,
        ):
            cancel_future = self._goal_handle.cancel_goal_async()
            cancel_future.add_done_callback(lambda _: self._send_pending())
        else:
            self._send_pending()

    def _send_pending(self):
        if self._pending_pose is None:
            return
        pose = self._pending_pose
        self._pending_pose = None
        goal = NavigateToPose.Goal()
        goal.pose = pose
        future = self._client.send_goal_async(goal)
        future.add_done_callback(self._goal_response)

    def _goal_response(self, future):
        handle = future.result()
        if handle is None or not handle.accepted:
            self.get_logger().error('NavigateToPose goal rejected.')
            return
        self._goal_handle = handle
        self.get_logger().info('NavigateToPose goal accepted; Smac planner will generate the global path.')
        result_future = handle.get_result_async()
        result_future.add_done_callback(self._goal_result)

    def _goal_result(self, future):
        try:
            result = future.result()
            self.get_logger().info(f'NavigateToPose finished with status={result.status}')
        except Exception as exc:  # pragma: no cover - runtime diagnostic
            self.get_logger().error(f'NavigateToPose result error: {exc}')
        finally:
            self._goal_handle = None


def main(args=None):
    rclpy.init(args=args)
    node = TrolleyGoalForwarder()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
